### ISSUE TITLE
USER STORY: Special events

### ISSUE THREAD

**Issue by Welshy92** [Welshy92/My-First-Agile-Project#5]
As an **administrator**, I can **display special events** so that **users know when and where they happen**

## Acceptance Criteria:
* An event title is can be chosen
* The event description can be entered
* The event location can be edited
* The date and time that the event takes place can be edited

## Tasks:
* [ ] Design UI for text and date entries entries of event details.
* [ ] Create HTML form.
* [ ] Create CSS styling for form.
* [ ] Create backend to store information.
* [ ] Connect front end to back end to display info to user.
* [ ] Test form functionality.
* [ ] Test information being displayed correctly to the user.
