### ISSUE TITLE
USER STORY: Newsletter signup

### ISSUE THREAD

**Issue by Welshy92** [Welshy92/My-First-Agile-Project#6]
As a **user**, I can **sign up to a newsletter** so that **I can be kept upto date with the newest events and opinion polls**

## Acceptance Criteria:
* I am told what the newsletters are for
* I am told how often they are emailed
* I can enter a name
* I can enter a valid email address

## Tasks:
* [ ] Design UI element for submission form.
* [ ] Create HTML form.
* [ ] Create CSS styling.
* [ ] Create adding info to external file.
* [ ] Test Submission to see if data is added to external file.

**Comment by Welshy92** [comment]
This is completed
