### ISSUE TITLE
USER STORY: Reviews

### ISSUE THREAD

**Issue by Welshy92** [Welshy92/My-First-Agile-Project#7]
As a **user**, I can **leave a review** so that **other users can see what I think about the club**

## Acceptance Criteria:
* A name or username can be entered.
* A small picture can be uploaded to use.
* A rating of 0 to 5 stars can be given.
* A descriptive review can be given.
* A 500 character limit is enforced for the review.

## Tasks:
* [ ] Design UI for a review form.
* [ ] Design display for recent reviews.
* [ ] Create HTML form.
* [ ] Create Upload image.
* [ ] Create CSS styling.
* [ ] Store image.
* [ ] Store review data.
* [ ] Create Javascript to show recent data + image to users.
* [ ] Create Javascript to show average review score.
* [ ] Test Form.
* [ ] Test recent reviews + average score being shown.
